### ISSUE TITLE
mft缺少，以及rocksdb依赖包无法成功获取

### ISSUE THREAD

**Issue by phmsforever** [fansehep/ShaunDB#2]
---------------------------------

**Comment by fansehep** [comment]
> phmsforever

你好,
master 分支的 rocksdb 依赖我没有写完, 所以构建会有问题, rocksdb 默认是使用 cmake 构建的, 如果要加入到 bazel 构建系统中需要自己编写 BUILD.bazel 文件, 所以如果你想构建 master 分支，暂时可能需要自己安装一下 rocksdb, 例如 apt, 或者编译安装, 感兴趣可以来帮忙做一下这方面的工作.

new_arch 分支我同时支持了 cmake build 和 bazel build, cmake 这里我上周推送代码的时候，是使用 submodule 方式来管理依赖的, 但是忘记add 到那一次 commit 中去了, 所以可能 new_arch 会有点问题, 但是, new_arch 的 sql-parser 部分目前我没写完, 所以可能就算能编译工具链ok，但仍然会存在编译问题.

关于这里的 master libfmt 编译问题是因为我当时依赖了 master 分支的 libfmt, 后面他们好像做出了一些 break API 的改进, 这里 可能有点问题, 如果你有需求的话，我觉得稳定在 libfmt 9.1 是一个不错的选择.

**Comment by phmsforever** [comment]
请问您这环境到底啥样的啊，上个问题解决了，现在这个编译说C++版本的问题，我采用clang 10,网上也说兼容C++20 ，关键不管怎么调试-std=c++0x，基本上都不变，一直有问题
ERROR: /home/p/ShaunDB-main/src/base/test/BUILD.bazel:5:8: Compiling src/base/test/logfile_test.cpp failed: (Exit 1): clang failed: error executing command /usr/lib/llvm-10/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 39 arguments skipped)


Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from src/base/test/logfile_test.cpp:1:
In file included from ./src/base/log/logfile.hpp:10:
./src/base/timestamp.hpp:8:10: fatal error: 'compare' file not found
#include <compare&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^~~~~~~~~
1 error generated.
INFO: Elapsed time: 95.956s, Critical Path: 0.42s
INFO: 57 processes: 57 internal.
FAILED: Build did NOT complete successfully




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fansehep/ShaunDB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月20日(星期天) 凌晨0:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fansehep/ShaunDB] mft缺少，以及rocksdb依赖包无法成功获取 (Issue #2)





  
phmsforever
  
你好,
 master 分支的 rocksdb 依赖我没有写完, 所以构建会有问题, rocksdb 默认是使用 cmake 构建的, 如果要加入到 bazel 构建系统中需要自己编写 BUILD.bazel 文件, 所以如果你想构建 master 分支，暂时可能需要自己安装一下 rocksdb, 例如 apt, 或者编译安装, 感兴趣可以来帮忙做一下这方面的工作.
 
new_arch 分支我同时支持了 cmake build 和 bazel build, cmake 这里我上周推送代码的时候，是使用 submodule 方式来管理依赖的, 但是忘记add 到那一次 commit 中去了, 所以可能 new_arch 会有点问题, 但是, new_arch 的 sql-parser 部分目前我没写完, 所以可能就算能编译工具链ok，但仍然会存在编译问题.
 
关于这里的 master libfmt 编译问题是因为我当时依赖了 master 分支的 libfmt, 后面他们好像做出了一些 break API 的改进, 这里 可能有点问题, 如果你有需求的话，我觉得稳定在 libfmt 9.1 是一个不错的选择.
